### ISSUE TITLE
Splitter to Merger conveyor being read backwards?

### ISSUE THREAD

**Issue by Crimjims** [MarcioHuser/EfficiencyCheckerMod#14]
Hi, love the idea of this mod and am hoping to get a lot of use out of it to debug any stuttering or overflow on my setup. However in trying it out I ran into the below odd issue. Very simple setup of:

- 2 Iron rod constructor running at 100%
- Both run out Mk1 Conveyors at 15ppm each
- First constructor is fed to a splitter onto 3 Mk1 conveyors at 5ppm each
- 2 of these splits are combined to give 10ppm into a Screw constructor (This is read correctly as INPUT: 10, OUTPUT: 10)
- 1 of these splits merges with the second belt to give a 20ppm line into a Rotor constructor
- Line to the rotor constructor is reading at INPUT: 10
- Line between the splitter and the second belt merger is reading at INPUT: -5

On the two identical but mirrored setups for this I have checked, it gives the same result.
<img width="514" alt="ECM Issue 2" src="https://github.com/MarcioHuser/EfficiencyCheckerMod/assets/40436763/9aab7531-cf1f-403a-aaf8-1149cd7fc8cf">
<img width="635" alt="ECM Issue 1" src="https://github.com/MarcioHuser/EfficiencyCheckerMod/assets/40436763/1cdba3ca-9b6c-4583-aded-9895a3ca110e">

Is there anything I can do to get this to read correctly without a custom input, since that would kind of defeat the debugging point?

**Comment by MarcioHuser** [comment]
Oh, no, no, it doesn't handle well splitting and remerging (load-balancing). It get TOTALLY lost in those kind of scenario. I simply gave up trying to solve that kind of issue, since it was made to help MY playstyle of pure manifolding

**Comment by Crimjims** [comment]
Fair enough - it works well for manifolds when I tested those! Oddly enough it handles more complex splitting well enough too (eg; a 5-split of [Merge]->[Split-2]->[Split-3]->[One back to Merge]) reads correctly as 1/5th, 1/5th, 3/5ths - it's only when that then merges with another line is there an issue, yeah.

Ah well. it's still useful enough for debugging since I can trace back to where the error in numbers comes in, and use that to verify forward.
