### ISSUE TITLE
Wrong "injected input"- Conveyor Belt speed is not taken into account

### ISSUE THREAD

**Issue by Kubrix** [MarcioHuser/EfficiencyCheckerMod#2]
Stable branch CL#131382
Mod version 1.0.5

Given: Miner Mk.1 on pure node  100% Clock Speed = 120 items/minute mining speed
https://imgur.com/a/eFOOOeS

Miner is connected to Splitter using Mk.1 belt, which transfer only 60 items/minute
Efficiency Checker is connected to that belt between miner and splitter.

Expected flow rate (injected input) to be shown on Checker - 60 (Mk.1 belt limitation)
Flow rate shown on Checker: 120 https://imgur.com/7k0Mjnq

**Comment by MarcioHuser** [comment]
this is correct. If the items are not going to be consumed from the other side of the splitter, the inject input will show the full number. It does not and will NEVER limit the injected input by the belt limit. If you have injected input greater than the belt limit, it will highlight it with a yellow background

**Comment by Kubrix** [comment]
**If the items are not going to be consumed from the other side of the splitter, the inject input will show the full number**
**If you have injected input greater than the belt limit, it will highlight it with a yellow background**
Ok. I have added 2 Smelters after splitter and both Smelters output in 1 container. Buildings are connected using Mk1 belts.
https://imgur.com/a/HkbxWx4

The Miner->Checker->Splitter should work at 60items per mimute (belt limit) 
Cheker dashboard:
https://imgur.com/a/b9EYlOC

What does it give me?
90 items per minute required by 2 refineries
120 items can be outputted by miner.
Injected input greater than the belt limit
 
But my main question remiains unanswered: What is the current flow of items for this Miner-splitter belt?

**Comment by MarcioHuser** [comment]
You have slow belts feeding in. Anyway:

- the belt before the splitter would read: 120 / 60 / 90 (45 from each smelter later on) - this mean you have slow belts to feed everything (at least for the belt before the splitter)
- each belt after the splitter would read: 75 (120 - 45 that are required for the "other side") / 60 / 45
