### ISSUE TITLE
Conveyor Belt speed is not taken into account 2

### ISSUE THREAD

**Issue by Kubrix** [MarcioHuser/EfficiencyCheckerMod#3]
Previous issue (https://github.com/MarcioHuser/EfficiencyCheckerMod/issues/2)  is closed so I created a new one.

**If the items are not going to be consumed from the other side of the splitter, the inject input will show the full number**
**If you have injected input greater than the belt limit, it will highlight it with a yellow background**
Ok. I have added 2 Smelters after splitter and both Smelters output in 1 container. Buildings are connected using Mk1 belts.
https://imgur.com/a/HkbxWx4

The Miner->Checker->Splitter should work at 60items per mimute (belt limit) 
Cheker dashboard:
https://imgur.com/a/b9EYlOC

What does it give me?
90 items per minute required by 2 refineries
120 items can be outputted by miner.
Injected input greater than the belt limit
 
But my main question remiains unanswered: What is the current flow of items for this Miner-splitter belt?

**Comment by MarcioHuser** [comment]
You have slow belts feeding in.

Anyway:

the belt before the splitter would read: 120 / 60 / 90 (45 from each smelter later on) - this mean you have slow belts to feed everything (at least for the belt before the splitter)
each belt after the splitter would read: 75 (120 - 45 that are required for the "other side") / 60 / 45
