### ISSUE TITLE
Possible calculation based on actual decvice efficiency instead theoretical

### ISSUE THREAD

**Issue by esvarc** [MarcioHuser/EfficiencyCheckerMod#4]
Calculation should be done based on device efficiency. Or there could be posibility to have to switch to calculate requried output based on pissible need when device runs at 100% efficiency or calculated by actual efficiency.

Some of my Manufacturers actually work on stock and stop producing when target container is full, but efficency checker shows required imput for chain with fully running manufacturer at the ond of production line. Workaround is set clock speed to 0 on manufacturer, but then I need go back and put clock speed at 100% when I pick any produced item from connected container.

**Comment by MarcioHuser** [comment]
It is working as intented, it shows MAXIMUM potentials if everything runs at 100% all the time. And that will never change
