### ISSUE TITLE
[BUG] Crashing when placing a checker in a pipe

### ISSUE THREAD

**Issue by Riggola** [MarcioHuser/EfficiencyCheckerMod#5]
Hello,
Im playing with another player, im the host, the crash occured when im placing the checker pipe with the method you pointing to the checker above and it will place it exactly in the same position

Screenshot when it dont crash: http://prntscr.com/vvxq5m
Screenshot when it crash while updating the checker: http://prntscr.com/vvxqpj < here im pointing with mouse the checker below the pipe i want to place it
The crashlog is more dettailed now because i reproduced it on my pc, the other one was when my friend placed it
CrashLog: https://pastebin.com/GgMMhrXM

**Comment by MarcioHuser** [comment]
Update the mod and check if it still crashes

**Comment by Riggola** [comment]
ty fixxed
