### ISSUE TITLE
[Info] Item checker + 3x source material + 2x required output

### ISSUE THREAD

**Issue by Riggola** [MarcioHuser/EfficiencyCheckerMod#6]
Hello, 
it is hard to explain for me since english is not my fisrt language so i will try to explain it with screenshot

This is what the checker detect: http://prntscr.com/vvxsaf
This is the inject source: http://prntscr.com/vvxtww
This is the required output: http://prntscr.com/vvxufk
The output of assemblers mk4 are  751.5 + 751.5 + 900
it is normal to get those info from the checker?

**Comment by MarcioHuser** [comment]
those numbers are crazy, but can happen, if you have belts splitting and re-merging after the checker

**Comment by Riggola** [comment]
assembler 1 and assembler 3 are merged with the output of assembler 2 (the middle one) and those 2 belts go to 2 different splitter and then go both to a manufactur

**Comment by Riggola** [comment]
http://prntscr.com/vvzitb oh wait i mean, the limited throughput is 2000 because i have mk6 belt mod, the required output is right because the 2 manufacturer require 2252 quickwire to work, and the inject input should be 2400.3 and not 150.75 so the problem is only with the injected input, there is no possible to fix/add that kind of system belts?

**Comment by MarcioHuser** [comment]
Yeah, I've seen that kind of setup before. You are splitting/mergine before each checker and double feeding the manufactores. The checkers can't make heads-or-tails from that, it is too exotic for then to handle 🤷‍♂️

**Comment by Riggola** [comment]
ahhhh okay then i can close thank you

**Comment by Riggola** [comment]
Hello, i didnt want to open another issue so i will ask here, it is possible to make checker to ignore in the required output standby or unpowered machine?

**Comment by MarcioHuser** [comment]
I will consider that, but right now it is not within its scope

**Comment by Riggola** [comment]
Yeah, but in my case I have 2/3 build linked to a system of belt or pipe that is producing only when I need those items, I mean I have a packager linked to my fuel production that only keep 500 fuel canister in and when I need them I just take it (it produce that item just 5 minute every 2/3 days but it is still included in the output required, this is just one esample, if the checker could detect the state of the build and smartly change the value that would be very good, I don’t know how much the game api is flexible so I don’t know if it possible to get the standby status or the no power status, I just suggesting things, the mod is already perfect in this state, since I started use it now I’m unable to go back! Good job!
