### ISSUE TITLE
Efficiency Checker Mod

### ISSUE THREAD

**Issue by fijili** [MarcioHuser/EfficiencyCheckerMod#7]
dont work  mod build 138299 steam build 138516  update pls thx

**Comment by MarcioHuser** [comment]
Define "don't work": does it crash? Are you using the latest, version 1.1.5?

**Comment by fijili** [comment]
latest version installed unlock logistics mk3 mod dont open

**Comment by MarcioHuser** [comment]
You unlocked logistics mk3 already and it does not show the new miletone on the HUB, called "Efficiency Checker"? (same Tier as Logistics MK3)

**Comment by fijili** [comment]
yes does not show

**Comment by fijili** [comment]
#

**Comment by MarcioHuser** [comment]
Have you scrolled sideways? It may be hidden due to "too many" milestones

**Comment by MarcioHuser** [comment]
Can you send me your SatisfactoryModLoader.log file, at the root of the game folder?

**Comment by fijili** [comment]
![Uploading 1.jpg…]()

**Comment by fijili** [comment]
![Uploading 2.jpg…]()

**Comment by fijili** [comment]
![3](https://user-images.githubusercontent.com/75621976/101363842-8ad8ec80-38aa-11eb-9301-f9ed9ef6aafc.jpg)

**Comment by MarcioHuser** [comment]
Well, I will have  a look on that when I can. You are the first that ever complaints about that

**Comment by fijili** [comment]
![1](https://user-images.githubusercontent.com/75621976/101364063-d1c6e200-38aa-11eb-8670-05833fc07592.jpg)

**Comment by fijili** [comment]
![2](https://user-images.githubusercontent.com/75621976/101364106-e1462b00-38aa-11eb-99c6-574ea1f3b224.jpg)

**Comment by MarcioHuser** [comment]
According to your previous capture, you haven't unlocked yet the Logisitcs Mk3 milestone. Once you send away the drop ship to unlock it, the milestone for Efficiency Checker should show up

**Comment by fijili** [comment]
[SatisfactoryModLoader.log](https://github.com/MarcioHuser/EfficiencyCheckerMod/files/5653322/SatisfactoryModLoader.log)

**Comment by fijili** [comment]
How do I get it:
It will become available to be unlocked at the hub once you have unlocked the Logistics Mk.3 milestone

picture 3 it did not open mk3 unlocked

**Comment by MarcioHuser** [comment]
You have to keep progressing. You still don't have mk3 belts available to built. Once you have it, a new milestone will show up in Tier 4 at the hub, to unlock Efficiency Checker. You have to continue your progress to unlock steel, to be able to make steel beans and steel pipes, so that you can use then to unlock Logistics Mk3, that will give you mk3 belts/lifts, lasrge storage containers and stackable pipe supports

**Comment by fijili** [comment]
I opened it all in another game then it didn't come out

**Comment by fijili** [comment]
It will become available to be unlocked at the hub once you have unlocked the Logistics Mk.3 milestone 
you wrote  i unlocked mk3

**Comment by fijili** [comment]
the advanced stages of production mod doesn't make more sense to buy mk1

**Comment by fijili** [comment]
my english is not very good sorry

**Comment by fijili** [comment]
thx

**Comment by MarcioHuser** [comment]
![image](https://user-images.githubusercontent.com/68478105/102027435-e0b60480-3d82-11eb-81f1-a858a9bfa640.png)

![image](https://user-images.githubusercontent.com/68478105/102027422-c3813600-3d82-11eb-912a-3fc66d19c76a.png)

I started a new save and make the progression to unlock Logistics Mk3. After that, the milestone for Efficiency Checker shows as supposed to

**Comment by MarcioHuser** [comment]
This error cannot be reproduced
