### ISSUE TITLE
Game Freezes while Calulating

### ISSUE THREAD

**Issue by Diestroy** [MarcioHuser/EfficiencyCheckerMod#9]
I'm on EA 139586(Epic) with SML 2.2.1 and SMM 2.3.1.
Mod Version set to latest. So its 1.1.5
Multiplayer (tested with and without other players)

When I use your Mod (must have MOD in my opinion) the game freezes for like full 1 to 2 min. when the checker is calculating.
Happen when in close proximity, on initial installation (on belt) and when interacting with the checker.

Maybe it's an incompatibility with the new version or something like that. Who am I to tell I can only manage "Hello World" :D 

If You have an Idea or a fix it would be great. I got so used to your mod it's something the game should have had to begin with.

Greetings
Tom

**Comment by MarcioHuser** [comment]
Does it freeze and keep running or freeze and than crash?

**Comment by MarcioHuser** [comment]
Try enabling the trace log: go to the game folder -> configs -> open the EfficiencyChecker.cfg and change the **dumpConnections** flag from **false** to **true**. Run the game again, provoke the issue and send the %localappdata%\FactoryGame\Saved\Logs\FactoryGame.log right after the game is responding again. Save it to Pastebin or Google Drive and share the link here

**Comment by Diestroy** [comment]
Sorry took so long to answer but needed some sleep last night.

[Here the link for the log file on Google Drive.](https://drive.google.com/file/d/1Z73MQh5iviya0sWaf58rzJChwtK1kamM/view?usp=sharing) It's 1.3Gb big!

Maybe you can make something out of it.

**Comment by MarcioHuser** [comment]
You could have zipped it 😅 But that's ok

**Comment by MarcioHuser** [comment]
Oh, boy! Yep, nothing that can be done there. You have your whole factory sharing the same belt system regulated by smart splitters? Because looks like the code has to traverse through thousands of belts, smart splitters and machines to work it all out

**Comment by Diestroy** [comment]
Ok but it worked bevor. May it be possible that it has to do something with the SlowItDown MOD. 
We have some big Production lines and use many splitters and smartsplitters. I will do some testing on my side. 
If you want close it for now. If I find something I will come back and tell you.

Thanks for the help so far. 

Can't wait for future updates.

**Comment by MarcioHuser** [comment]
The issue is unsolvable; your production line (the amount of interconcted belts/lifts/mergers/splitters) is too big and too deep, even causing errors that the code can't solve (it would crash before, now it just show an error message on the checker display)
